trigger:
  - main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      version: '6.0.400'  # Remplacez par la version .NET désirée

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: 'test'
      projects: '**/*Tests.csproj'
      arguments: '--configuration $(buildConfiguration)'
  
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '18.x'

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: 'Install Angular CLI and Dependencies'
    workingDirectory: '$(System.DefaultWorkingDirectory)/app'
    
  - script: echo $(System.DefaultWorkingDirectory)
    
  - script: |
      ng build
    displayName: 'Build Angular Application'
    workingDirectory: '$(System.DefaultWorkingDirectory)/app'

  - script: |
      ng test
    displayName: 'Run Angular Unit Tests'