trigger:
  - main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '18.x'
    
  - script: |
      cd $(System.DefaultWorkingDirectory)/app
      npm install
      ng build
    displayName: 'Build Angular Application'

  - script: |
      cd $(System.DefaultWorkingDirectory)/app
      ng test --watch=false
    displayName: 'Run Angular Unit Tests'
    
  - task: UseDotNet@2
    inputs:
      version: '6.0.400'  # Remplacez par la version .NET désirée

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: 'test'
      projects: '**/*Tests.csproj'
      arguments: '--configuration $(buildConfiguration)'